# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/barbet/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),barbet)

$(call add-radio-file-sha1-checked,radio/abl.img,4fe249b8c1cb891780ec4e0b5a3afa32850d5ec2)
$(call add-radio-file-sha1-checked,radio/aop.img,f2b2f7a162a5690fbd860bc2118080b4d82b663c)
$(call add-radio-file-sha1-checked,radio/devcfg.img,27245da069735a882266169db0c9487ef7153ddf)
$(call add-radio-file-sha1-checked,radio/featenabler.img,a360f00622f742f2f68d4b942d8ef7b5d5e378fb)
$(call add-radio-file-sha1-checked,radio/hyp.img,bd9ed2dea6f05f3aeb8d1a3c8ea1690ff345cecc)
$(call add-radio-file-sha1-checked,radio/keymaster.img,33657077c780ab44ed093754b32e4efd237a4a8f)
$(call add-radio-file-sha1-checked,radio/modem.img,448a36cf8c581446c646d50e52a238c27b8e96b4)
$(call add-radio-file-sha1-checked,radio/qupfw.img,4e11835066ce32ccf819ab828e6a2c9514070a82)
$(call add-radio-file-sha1-checked,radio/tz.img,84b33110fb869efc117ad618a045a571cbadb1ec)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,2a3e46e1c7ad11286e05add1fad27134296fc8b6)
$(call add-radio-file-sha1-checked,radio/xbl.img,01c2c287df6d9c0194def37953504a9fde94d55a)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,63af01a7c16382143d509f1ea5cbaec53a3ce1bd)

endif
