# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/barbet/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),barbet)

$(call add-radio-file-sha1-checked,radio/abl.img,feddc302dce61f7d038cd3e5d308ff131782bf51)
$(call add-radio-file-sha1-checked,radio/aop.img,a1e3f13cd133988b6cb9f8dda75ca9d6805cd456)
$(call add-radio-file-sha1-checked,radio/devcfg.img,f9d07972c22efa30818fb4e09ddf45b0d8d358f3)
$(call add-radio-file-sha1-checked,radio/featenabler.img,ea8ffb642180c4dde14e5e5801274a4d8d326851)
$(call add-radio-file-sha1-checked,radio/hyp.img,0ffe6303f0b44584b02a8e3ace208f97d0e5f889)
$(call add-radio-file-sha1-checked,radio/keymaster.img,1156bd6087ba81e5b0e1824af291d59d84286af8)
$(call add-radio-file-sha1-checked,radio/modem.img,b984628e8815a9bd1c0552f078171f14aabf47fb)
$(call add-radio-file-sha1-checked,radio/qupfw.img,9163702b46b6b4d33d601c3df0862a8178998162)
$(call add-radio-file-sha1-checked,radio/tz.img,3998df58183e62aa733df0091ee0b5e42108e8e6)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,20395b425b8388794cd59b236cadf6aa0f2074a9)
$(call add-radio-file-sha1-checked,radio/xbl.img,245ea7497b9ece038bfc4dff58731116fa7944ca)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,6d7f24da3c5925b099f759bf5c0134da789b358d)

endif
